In [74]:
import pandas as pd

df = pd.read_csv('./medical_raw_data.csv', index_col=0)
df.info()
for col in df.columns:
    print(f"--------{col}----------")
    # Check the data type of each column individually and the number of entries.
    print('Check the data type of each column individually')
    print(df[col].info())

    #Check the entries of the columns.
    print('--Check the entries of the columns--')
    print(df[col].unique())

    #check the quantity of each value. 
    print('--check the quantity of each value--')
    print(df[col].value_counts())
    
    #Check the number of missing entries.
    print('--Check the number of missing entries--')
    print(f"Number of missing values in {col}:", df[col].isnull().sum())

    #Check if data is within reasonable bounds.
    print('--Check if data is within reasonable bounds--')
    print(df[col].describe())

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 1 to 10000
Data columns (total 52 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CaseOrder           10000 non-null  int64
 1   Customer_id         10000 non-null  object
 2   Interaction         10000 non-null  object
 3   UID                 10000 non-null  object
 4   City                10000 non-null  object
 5   State               10000 non-null  object
 6   County              10000 non-null  object
 7   Zip                 10000 non-null  int64
 8   Lat                 10000 non-null  float64
 9   Lng                 10000 non-null  float64
 10  Population          10000 non-null  int64
 11  Area                10000 non-null  object
 12  Timezone            10000 non-null  object
 13  Job                 10000 non-null  object
 14  Children            7412 non-null   float64
 15  Age                 7586 non-null   float64
 16  Education           10000 non-null  object
 17  Employment          10000 non-null  object
 18  Income              7536 non-null   float64
 19  Marital             10000 non-null  object
 20  Gender              10000 non-null  object
 21  ReAdmis             10000 non-null  object
 22  VitD_levels         10000 non-null  float64
 23  Doc_visits          10000 non-null  int64
 24  Full_meals_eaten    10000 non-null  int64
 25  VitD_supp           10000 non-null  int64
 26  Soft_drink          7533 non-null   object
 27  Initial_admin       10000 non-null  object
 28  HighBlood           10000 non-null  object
 29  Stroke              10000 non-null  object
 30  Complication_risk   10000 non-null  object
 31  Overweight          9018 non-null   float64
 32  Arthritis           10000 non-null  object
 33  Diabetes            10000 non-null  object
 34  Hyperlipidemia      10000 non-null  object
 35  BackPain            10000 non-null  object
 36  Anxiety             9016 non-null   float64
 37  Allergic_rhinitis   10000 non-null  object
 38  Reflux_esophagitis  10000 non-null  object
 39  Asthma              10000 non-null  object
 40  Services            10000 non-null  object
 41  Initial_days        8944 non-null   float64
 42  TotalCharge         10000 non-null  float64
 43  Additional_charges  10000 non-null  float64
 44  Item1               10000 non-null  int64
 45  Item2               10000 non-null  int64
 46  Item3               10000 non-null  int64
 47  Item4               10000 non-null  int64
 48  Item5               10000 non-null  int64
 49  Item6               10000 non-null  int64
 50  Item7               10000 non-null  int64
 51  Item8               10000 non-null  int64
dtypes: float64(11), int64(14), object(27)
memory usage: 4.0+ MB
--------CaseOrder----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: CaseOrder
Non-Null Count  Dtype
--------------  -----
10000 non-null  int64
dtypes: int64(1)
memory usage: 156.2 KB
None
--Check the entries of the columns--
[    1     2     3 ...  9998  9999 10000]
--check the quantity of each value--
CaseOrder
1        1
6671     1
6664     1
6665     1
6666     1
        ..
3334     1
3335     1
3336     1
3337     1
10000    1
Name: count, Length: 10000, dtype: int64
--Check the number of missing entries--
Number of missing values in CaseOrder: 0
--Check if data is within reasonable bounds--
count    10000.00000
mean      5000.50000
std       2886.89568
min          1.00000
25%       2500.75000
50%       5000.50000
75%       7500.25000
max      10000.00000
Name: CaseOrder, dtype: float64
--------Customer_id----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Customer_id
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['C412403' 'Z919181' 'F995323' ... 'R778890' 'E344109' 'I569847']
--check the quantity of each value--
Customer_id
C412403    1
D294364    1
B203210    1
C20177     1
K216020    1
          ..
J694995    1
N704840    1
A197688    1
H115454    1
I569847    1
Name: count, Length: 10000, dtype: int64
--Check the number of missing entries--
Number of missing values in Customer_id: 0
--Check if data is within reasonable bounds--
count       10000
unique      10000
top       C412403
freq            1
Name: Customer_id, dtype: object
--------Interaction----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Interaction
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['8cd49b13-f45a-4b47-a2bd-173ffa932c2f'
 'd2450b70-0337-4406-bdbb-bc1037f1734c'
 'a2057123-abf5-4a2c-abad-8ffe33512562' ...
 '1d79569d-8e0f-4180-a207-d67ee4527d26'
 'f5a68e69-2a60-409b-a92f-ac0847b27db0'
 'bc482c02-f8c9-4423-99de-3db5e62a18d5']
--check the quantity of each value--
Interaction
8cd49b13-f45a-4b47-a2bd-173ffa932c2f    1
dc1799a6-61d1-44a3-9b94-b89584baddfc    1
dc6bab10-659b-4c78-ba87-87ffa3def32f    1
1cb70cc8-47b7-4192-8bed-faad0f27ab3b    1
06d0da86-5600-472d-a35d-7632775b5cd7    1
                                       ..
2d5c049d-0431-443f-a9d7-46f875998599    1
4ccc7838-5c2c-4a3c-9e3b-2a646cec157e    1
4767cd0e-626d-4c5a-834e-a948aba315c2    1
8b1e1ea3-e596-4a97-b2cb-7f9926e9fbee    1
bc482c02-f8c9-4423-99de-3db5e62a18d5    1
Name: count, Length: 10000, dtype: int64
--Check the number of missing entries--
Number of missing values in Interaction: 0
--Check if data is within reasonable bounds--
count                                    10000
unique                                   10000
top       8cd49b13-f45a-4b47-a2bd-173ffa932c2f
freq                                         1
Name: Interaction, dtype: object
--------UID----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: UID
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['3a83ddb66e2ae73798bdf1d705dc0932' '176354c5eef714957d486009feabf195'
 'e19a0fa00aeda885b8a436757e889bc9' ... '41b770aeee97a5b9e7f69c906a8119d7'
 '2bb491ef5b1beb1fed758cc6885c167a' '95663a202338000abdf7e09311c2a8a1']
--check the quantity of each value--
UID
3a83ddb66e2ae73798bdf1d705dc0932    1
5d85418e862aab28ed18975446153694    1
28970195a839f74e572d2f43bd7fcb71    1
24665d1c5070b579d0c190324599ca6d    1
2d42fd6803d96fcffe64d3fcaab430dc    1
                                   ..
ce28b38948f9737918e240d8ce6b275f    1
d98f314ddd12ca99e05858219127a06e    1
43e47521f56f27d0fc8e00ba7141de1b    1
ffd9be64812b5e36ba9367abe51be705    1
95663a202338000abdf7e09311c2a8a1    1
Name: count, Length: 10000, dtype: int64
--Check the number of missing entries--
Number of missing values in UID: 0
--Check if data is within reasonable bounds--
count                                10000
unique                               10000
top       3a83ddb66e2ae73798bdf1d705dc0932
freq                                     1
Name: UID, dtype: object
--------City----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: City
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['Eva' 'Marianna' 'Sioux Falls' ... 'Milmay' 'Quinn' 'Coraopolis']
--check the quantity of each value--
City
Houston             36
San Antonio         26
Springfield         22
New York            21
Miami               21
                    ..
Coyote               1
Tiline               1
Monon                1
Sullivans Island     1
Coraopolis           1
Name: count, Length: 6072, dtype: int64
--Check the number of missing entries--
Number of missing values in City: 0
--Check if data is within reasonable bounds--
count       10000
unique       6072
top       Houston
freq           36
Name: City, dtype: object
--------State----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: State
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['AL' 'FL' 'SD' 'MN' 'VA' 'OK' 'OH' 'MS' 'WI' 'IA' 'CA' 'IN' 'MO' 'MI'
 'NE' 'PA' 'AR' 'WV' 'KS' 'MA' 'KY' 'NY' 'VT' 'DC' 'IL' 'ND' 'SC' 'AK'
 'NM' 'NH' 'GA' 'NC' 'MD' 'TN' 'WA' 'TX' 'CO' 'NJ' 'LA' 'OR' 'AZ' 'ME'
 'ID' 'UT' 'RI' 'MT' 'PR' 'NV' 'CT' 'HI' 'WY' 'DE']
--check the quantity of each value--
State
TX    553
CA    550
PA    547
NY    514
IL    442
OH    383
MO    328
FL    304
VA    287
IA    276
MI    273
MN    267
NC    254
GA    247
KS    220
WI    214
KY    210
OK    207
WV    207
IN    195
AL    194
TN    194
WA    191
AR    190
NE    185
CO    179
NJ    176
LA    173
MA    149
MS    134
MD    131
SC    128
SD    123
ME    122
OR    122
MT    112
NM    110
ID    109
ND    108
AZ    108
CT     80
NH     79
UT     72
AK     70
VT     60
NV     51
WY     51
PR     43
HI     34
DE     17
RI     14
DC     13
Name: count, dtype: int64
--Check the number of missing entries--
Number of missing values in State: 0
--Check if data is within reasonable bounds--
count     10000
unique       52
top          TX
freq        553
Name: State, dtype: object
--------County----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: County
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['Morgan' 'Jackson' 'Minnehaha' ... 'Navarro' 'Los Alamos' 'Sterling']
--check the quantity of each value--
County
Jefferson      118
Washington     100
Franklin        93
Los Angeles     88
Montgomery      80
              ...
Jenkins          1
Sully            1
Panola           1
Kandiyohi        1
Sterling         1
Name: count, Length: 1607, dtype: int64
--Check the number of missing entries--
Number of missing values in County: 0
--Check if data is within reasonable bounds--
count         10000
unique         1607
top       Jefferson
freq            118
Name: County, dtype: object
--------Zip----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Zip
Non-Null Count  Dtype
--------------  -----
10000 non-null  int64
dtypes: int64(1)
memory usage: 156.2 KB
None
--Check the entries of the columns--
[35621 32446 57110 ...  8340 57775 15108]
--check the quantity of each value--
Zip
25674    4
78104    4
68355    4
62098    4
24136    4
        ..
18337    1
58442    1
71353    1
81612    1
15108    1
Name: count, Length: 8612, dtype: int64
--Check the number of missing entries--
Number of missing values in Zip: 0
--Check if data is within reasonable bounds--
count    10000.000000
mean     50159.323900
std      27469.588208
min        610.000000
25%      27592.000000
50%      50207.000000
75%      72411.750000
max      99929.000000
Name: Zip, dtype: float64
--------Lat----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Lat
Non-Null Count  Dtype
--------------  -----
10000 non-null  float64
dtypes: float64(1)
memory usage: 156.2 KB
None
--Check the entries of the columns--
[34.3496  30.84513 43.54321 ... 39.43609 44.10354 40.49998]
--check the quantity of each value--
Lat
36.06702    4
33.34798    4
35.25512    4
39.38610    4
37.86890    4
           ..
41.00911    1
39.20560    1
46.36035    1
34.96563    1
40.49998    1
Name: count, Length: 8588, dtype: int64
--Check the number of missing entries--
Number of missing values in Lat: 0
--Check if data is within reasonable bounds--
count    10000.000000
mean        38.751099
std          5.403085
min         17.967190
25%         35.255120
50%         39.419355
75%         42.044175
max         70.560990
Name: Lat, dtype: float64
--------Lng----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Lng
Non-Null Count  Dtype
--------------  -----
10000 non-null  float64
dtypes: float64(1)
memory usage: 156.2 KB
None
--Check the entries of the columns--
[ -86.72508  -85.22907  -96.63772 ...  -74.87302 -102.01593  -80.19959]
--check the quantity of each value--
Lng
-121.28753    4
-82.35159     4
-85.99134     4
-105.68001    4
-89.03658     4
             ..
-74.87894     1
-99.17911     1
-91.81854     1
-106.83727    1
-80.19959     1
Name: count, Length: 8601, dtype: int64
--Check the number of missing entries--
Number of missing values in Lng: 0
--Check if data is within reasonable bounds--
count    10000.000000
mean       -91.243080
std         15.205998
min       -174.209690
25%        -97.352982
50%        -88.397230
75%        -80.438050
max        -65.290170
Name: Lng, dtype: float64
--------Population----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Population
Non-Null Count  Dtype
--------------  -----
10000 non-null  int64
dtypes: int64(1)
memory usage: 156.2 KB
None
--Check the entries of the columns--
[ 2951 11303 17125 ...  8368  7908 41524]
--check the quantity of each value--
Population
0        109
195       14
115       11
178       11
285       11
        ...
8092       1
11147      1
27175      1
7371       1
41524      1
Name: count, Length: 5951, dtype: int64
--Check the number of missing entries--
Number of missing values in Population: 0
--Check if data is within reasonable bounds--
count     10000.000000
mean       9965.253800
std       14824.758614
min           0.000000
25%         694.750000
50%        2769.000000
75%       13945.000000
max      122814.000000
Name: Population, dtype: float64
--------Area----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Area
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['Suburban' 'Urban' 'Rural']
--check the quantity of each value--
Area
Rural       3369
Suburban    3328
Urban       3303
Name: count, dtype: int64
--Check the number of missing entries--
Number of missing values in Area: 0
--Check if data is within reasonable bounds--
count     10000
unique        3
top       Rural
freq       3369
Name: Area, dtype: object
--------Timezone----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Timezone
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['America/Chicago' 'America/New_York' 'America/Los_Angeles'
 'America/Indiana/Indianapolis' 'America/Detroit' 'America/Denver'
 'America/Nome' 'America/Anchorage' 'America/Phoenix' 'America/Boise'
 'America/Puerto_Rico' 'America/Yakutat' 'Pacific/Honolulu'
 'America/Menominee' 'America/Kentucky/Louisville'
 'America/Indiana/Vincennes' 'America/Toronto' 'America/Indiana/Marengo'
 'America/Indiana/Winamac' 'America/Indiana/Tell_City' 'America/Sitka'
 'America/Indiana/Knox' 'America/North_Dakota/New_Salem'
 'America/Indiana/Vevay' 'America/Adak' 'America/North_Dakota/Beulah']
--check the quantity of each value--
Timezone
America/New_York                  3889
America/Chicago                   3771
America/Los_Angeles                937
America/Denver                     612
America/Detroit                    262
America/Indiana/Indianapolis       151
America/Phoenix                    100
America/Boise                       86
America/Anchorage                   50
America/Puerto_Rico                 43
Pacific/Honolulu                    34
America/Menominee                   14
America/Nome                        12
America/Indiana/Vincennes            8
America/Kentucky/Louisville          6
America/Sitka                        6
America/Toronto                      5
America/Indiana/Marengo              3
America/Indiana/Tell_City            3
America/North_Dakota/Beulah          2
America/Yakutat                      1
America/Indiana/Winamac              1
America/Indiana/Knox                 1
America/North_Dakota/New_Salem       1
America/Indiana/Vevay                1
America/Adak                         1
Name: count, dtype: int64
--Check the number of missing entries--
Number of missing values in Timezone: 0
--Check if data is within reasonable bounds--
count                10000
unique                  26
top       America/New_York
freq                  3889
Name: Timezone, dtype: object
--------Job----------
Check the data type of each column individually
<class 'pandas.core.series.Series'>
Index: 10000 entries, 1 to 10000
Series name: Job
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 156.2+ KB
None
--Check the entries of the columns--
['Psychologist, sport and exercise' 'Community development worker'
 'Chief Executive Officer' 'Early years teacher'
 'Health promotion specialist' 'Corporate treasurer' 'Hydrologist'
 'Psychiatric nurse' 'Computer games developer'
 'Production assistant, radio' 'Contractor'
 'Surveyor, planning and development'
 'English as a second language teacher' 'Actuary' 'Media planner'
 'Fast food restaurant manager' 'Horticulturist, commercial'
 'Secretary, company' 'Designer, graphic' 'Personnel officer'
 'Telecommunications researcher' 'Restaurant manager, fast food'
 'Surveyor, minerals' 'Architectural technologist'
 'Therapist, speech and language' 'Accounting technician'
 'Glass blower/designer' 'Travel agency manager' 'Illustrator'
 'Police officer' 'Accountant, chartered public finance'
 'Sport and exercise psychologist' 'Pensions consultant'
 'Community education officer' 'Radio producer'
 'Designer, television/film set' 'Conference centre manager'
 'Advertising account executive' 'Civil Service fast streamer'
 'Training and development officer' 'Buyer, retail' 'Event organiser'
 'IT technical support officer'
 'Historic buildings inspector/conservation officer'
 'Research scientist (physical sciences)' 'Games developer'
 'Manufacturing engineer' 'Embryologist, clinical' 'Merchant navy officer'
 'Television floor manager' 'Web designer' 'Industrial buyer' 'Aid worker'
 'Systems developer' 'Probation officer'
 'Scientific laboratory technician' 'Environmental health practitioner'
 'Prison officer' 'Naval architect' 'Pilot, airline'
 'Medical sales representative' 'Learning disability nurse'
 'Agricultural engineer' 'Multimedia programmer' 'Cartographer'
 'Company secretary' 'Operations geologist' 'Conservation officer, nature'
 'Therapist, art' 'Therapist, sports' 'Oncologist'
 'Armed forces logistics/support/administrative officer' 'Podiatrist'
 'Translator' 'Geochemist' 'Engineer, technical sales'
 'Production designer, theatre/television/film' 'Site engineer'
 'Teacher, primary school' 'Clinical molecular geneticist'
 'Armed forces operational officer' 'Careers information officer'
 'Camera operator' 'Engineer, aeronautical' 'Learning mentor'
 'Neurosurgeon' 'Clothing/textile technologist' 'Financial controller'
 'Education officer, museum' 'Set designer'
 'Accountant, chartered certified' 'Solicitor' 'Forensic psychologist'
 'Outdoor activities/education manager' 'Heritage manager'
 'Hospital doctor' 'Engineer, chemical' 'Musician'
 'Engineer, control and instrumentation' 'Engineer, mining'